import type { NewsSource } from '@/types'

export const NEWS_SOURCES: NewsSource[] = [
  // ── United Kingdom ─────────────────────────────────────────────
  {
    id: 'bbc-news',
    name: 'BBC News',
    country: 'GB',
    lat: 51.5194,
    lng: -0.1270,
    url: 'https://www.bbc.com/news',
    rssUrl: 'http://feeds.bbci.co.uk/news/rss.xml',
    newsApiId: 'bbc-news',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'British public service broadcaster',
  },
  {
    id: 'the-guardian',
    name: 'The Guardian',
    country: 'GB',
    lat: 51.5345,
    lng: -0.1231,
    url: 'https://www.theguardian.com',
    rssUrl: 'https://www.theguardian.com/world/rss',
    newsApiId: 'the-guardian-uk',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'British daily newspaper',
  },
  {
    id: 'reuters',
    name: 'Reuters',
    country: 'GB',
    lat: 51.5010,
    lng: -0.0145,
    url: 'https://www.reuters.com',
    newsApiId: 'reuters',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'International news organization',
  },
  // ── United States ───────────────────────────────────────────────
  {
    id: 'the-new-york-times',
    name: 'The New York Times',
    country: 'US',
    lat: 40.7561,
    lng: -73.9903,
    url: 'https://www.nytimes.com',
    rssUrl: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
    newsApiId: 'the-new-york-times',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'American daily newspaper based in New York City',
  },
  {
    id: 'the-washington-post',
    name: 'The Washington Post',
    country: 'US',
    lat: 38.9041,
    lng: -77.0227,
    url: 'https://www.washingtonpost.com',
    newsApiId: 'the-washington-post',
    type: 'newsapi',
    category: 'politics',
    articleCount: 0,
    language: 'en',
    description: 'American daily newspaper based in Washington DC',
  },
  {
    id: 'cnn',
    name: 'CNN',
    country: 'US',
    lat: 33.7490,
    lng: -84.3880,
    url: 'https://www.cnn.com',
    rssUrl: 'http://rss.cnn.com/rss/edition_world.rss',
    newsApiId: 'cnn',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'American news television channel',
  },
  {
    id: 'associated-press',
    name: 'Associated Press',
    country: 'US',
    lat: 40.7484,
    lng: -73.9967,
    url: 'https://apnews.com',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'American not-for-profit news agency',
  },
  {
    id: 'npr-news',
    name: 'NPR News',
    country: 'US',
    lat: 38.9001,
    lng: -77.0424,
    url: 'https://www.npr.org/sections/news/',
    rssUrl: 'https://feeds.npr.org/1001/rss.xml',
    newsApiId: 'npr',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'American public radio network',
  },
  {
    id: 'fox-news',
    name: 'Fox News',
    country: 'US',
    lat: 40.7589,
    lng: -73.9851,
    url: 'https://www.foxnews.com',
    rssUrl: 'https://moxie.foxnews.com/google-publisher/latest.xml',
    newsApiId: 'fox-news',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'American conservative news network',
  },
  {
    id: 'politico',
    name: 'Politico',
    country: 'US',
    lat: 38.8951,
    lng: -77.0364,
    url: 'https://www.politico.com',
    rssUrl: 'https://rss.politico.com/politics-news.xml',
    newsApiId: 'politico',
    type: 'rss',
    category: 'politics',
    articleCount: 0,
    language: 'en',
    description: 'American political journalism organization',
  },
  // ── France ─────────────────────────────────────────────────────
  {
    id: 'le-monde',
    name: 'Le Monde',
    country: 'FR',
    lat: 48.8344,
    lng: 2.3964,
    url: 'https://www.lemonde.fr',
    rssUrl: 'https://www.lemonde.fr/rss/une.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'fr',
    description: 'French daily newspaper',
  },
  {
    id: 'france-24',
    name: 'France 24',
    country: 'FR',
    lat: 48.8452,
    lng: 2.2290,
    url: 'https://www.france24.com',
    rssUrl: 'https://www.france24.com/en/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'French international news television network',
  },
  // ── Germany ────────────────────────────────────────────────────
  {
    id: 'der-spiegel',
    name: 'Der Spiegel',
    country: 'DE',
    lat: 53.5461,
    lng: 9.9997,
    url: 'https://www.spiegel.de/international/',
    rssUrl: 'https://www.spiegel.de/international/index.rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'de',
    description: 'German news magazine',
  },
  {
    id: 'dw-news',
    name: 'Deutsche Welle',
    country: 'DE',
    lat: 50.7374,
    lng: 7.0982,
    url: 'https://www.dw.com/en/',
    rssUrl: 'https://rss.dw.com/xml/rss-en-all',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: "Germany's international broadcaster",
  },
  // ── Qatar / Middle East ────────────────────────────────────────
  {
    id: 'al-jazeera-english',
    name: 'Al Jazeera',
    country: 'QA',
    lat: 25.3548,
    lng: 51.1839,
    url: 'https://www.aljazeera.com',
    rssUrl: 'https://www.aljazeera.com/xml/rss/all.xml',
    newsApiId: 'al-jazeera-english',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Qatari state-funded international news network',
  },
  // ── Japan ──────────────────────────────────────────────────────
  {
    id: 'nhk-world',
    name: 'NHK World',
    country: 'JP',
    lat: 35.6938,
    lng: 139.7329,
    url: 'https://www3.nhk.or.jp/nhkworld/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: "Japan's international public broadcaster",
  },
  {
    id: 'japan-times',
    name: 'The Japan Times',
    country: 'JP',
    lat: 35.6693,
    lng: 139.7568,
    url: 'https://www.japantimes.co.jp',
    rssUrl: 'https://www.japantimes.co.jp/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: "Japan's oldest English-language newspaper",
  },
  // ── China ──────────────────────────────────────────────────────
  {
    id: 'xinhua-news',
    name: 'Xinhua News Agency',
    country: 'CN',
    lat: 39.9085,
    lng: 116.3975,
    url: 'http://www.xinhuanet.com/english/',
    rssUrl: 'http://www.xinhuanet.com/english/rss/worldrss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Chinese state news agency',
  },
  {
    id: 'south-china-morning-post',
    name: 'South China Morning Post',
    country: 'HK',
    lat: 22.2783,
    lng: 114.1747,
    url: 'https://www.scmp.com',
    rssUrl: 'https://www.scmp.com/rss/91/feed',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Hong Kong-based English-language newspaper',
  },
  // ── Russia ─────────────────────────────────────────────────────
  {
    id: 'rt-news',
    name: 'RT (Russia Today)',
    country: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    url: 'https://www.rt.com',
    rssUrl: 'https://www.rt.com/rss/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Russian state-controlled international television network',
  },
  // ── India ──────────────────────────────────────────────────────
  {
    id: 'the-hindu',
    name: 'The Hindu',
    country: 'IN',
    lat: 13.0827,
    lng: 80.2707,
    url: 'https://www.thehindu.com',
    rssUrl: 'https://www.thehindu.com/news/national/?service=rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Indian English-language daily newspaper',
  },
  {
    id: 'times-of-india',
    name: 'Times of India',
    country: 'IN',
    lat: 18.9750,
    lng: 72.8258,
    url: 'https://timesofindia.indiatimes.com',
    rssUrl: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms',
    newsApiId: 'the-times-of-india',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Indian English-language daily newspaper',
  },
  // ── Brazil ─────────────────────────────────────────────────────
  {
    id: 'folha-de-sao-paulo',
    name: 'Folha de S.Paulo',
    country: 'BR',
    lat: -23.5505,
    lng: -46.6333,
    url: 'https://www.folha.uol.com.br',
    rssUrl: 'https://feeds.folha.uol.com.br/emcimadahora/rss091.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'pt',
    description: 'Brazilian newspaper',
  },
  // ── Australia ──────────────────────────────────────────────────
  {
    id: 'abc-australia',
    name: 'ABC News Australia',
    country: 'AU',
    lat: -33.8688,
    lng: 151.2093,
    url: 'https://www.abc.net.au/news/',
    rssUrl: 'https://www.abc.net.au/news/feed/45910/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: "Australia's national public broadcaster",
  },
  // ── South Africa ───────────────────────────────────────────────
  {
    id: 'mail-and-guardian',
    name: 'Mail & Guardian',
    country: 'ZA',
    lat: -26.2041,
    lng: 28.0473,
    url: 'https://mg.co.za',
    rssUrl: 'https://mg.co.za/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'South African weekly newspaper',
  },
  // ── Canada ─────────────────────────────────────────────────────
  {
    id: 'cbc-news',
    name: 'CBC News',
    country: 'CA',
    lat: 45.4215,
    lng: -75.6972,
    url: 'https://www.cbc.ca/news',
    rssUrl: 'https://www.cbc.ca/cmlink/rss-topstories',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: "Canada's national public broadcaster",
  },
  // ── Italy ──────────────────────────────────────────────────────
  {
    id: 'la-repubblica',
    name: 'La Repubblica',
    country: 'IT',
    lat: 41.9028,
    lng: 12.4964,
    url: 'https://www.repubblica.it',
    rssUrl: 'https://www.repubblica.it/rss/homepage/rss2.0.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'it',
    description: 'Italian daily newspaper',
  },
  // ── Spain ──────────────────────────────────────────────────────
  {
    id: 'el-pais',
    name: 'El País',
    country: 'ES',
    lat: 40.4168,
    lng: -3.7038,
    url: 'https://elpais.com',
    rssUrl: 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'es',
    description: 'Spanish daily newspaper',
  },
  // ── Turkey ─────────────────────────────────────────────────────
  {
    id: 'hurriyet-daily-news',
    name: 'Hurriyet Daily News',
    country: 'TR',
    lat: 41.0082,
    lng: 28.9784,
    url: 'https://www.hurriyetdailynews.com',
    rssUrl: 'https://www.hurriyetdailynews.com/rss/home',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Turkish English-language newspaper',
  },
  // ── Additional Europe & Global Sources ─────────────────────────
  {
    id: 'politico-europe',
    name: 'Politico Europe',
    country: 'BE',
    lat: 50.8503,
    lng: 4.3517,
    url: 'https://www.politico.eu',
    rssUrl: 'https://www.politico.eu/feed/',
    type: 'rss',
    category: 'politics',
    articleCount: 0,
    language: 'en',
    description: 'European edition of Politico covering EU politics',
  },
  {
    id: 'euronews',
    name: 'Euronews',
    country: 'FR',
    lat: 45.7640,
    lng: 4.8357,
    url: 'https://www.euronews.com',
    rssUrl: 'https://www.euronews.com/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Pan-European news channel covering world and regional news',
  },
  {
    id: 'the-local-se',
    name: 'SVT Nyheter',
    country: 'SE',
    lat: 59.3293,
    lng: 18.0686,
    url: 'https://www.svt.se/nyheter',
    rssUrl: 'https://www.svt.se/nyheter/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sv',
    description: 'Swedish public broadcaster SVT news',
  },
  {
    id: 'the-local-no',
    name: 'NRK Nyheter',
    country: 'NO',
    lat: 59.9139,
    lng: 10.7522,
    url: 'https://www.nrk.no',
    rssUrl: 'https://www.nrk.no/toppsaker.rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'no',
    description: 'Norwegian public broadcaster NRK top stories',
  },
  {
    id: 'the-local-dk',
    name: 'DR Nyheder',
    country: 'DK',
    lat: 55.6761,
    lng: 12.5683,
    url: 'https://www.dr.dk/nyheder',
    rssUrl: 'https://www.dr.dk/nyheder/service/feeds/allenyheder',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'da',
    description: 'Danish public broadcaster DR all news',
  },
  {
    id: 'nltimes',
    name: 'NLTimes',
    country: 'NL',
    lat: 52.3676,
    lng: 4.9041,
    url: 'https://nltimes.nl',
    rssUrl: 'https://nltimes.nl/feed',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English news about the Netherlands',
  },
  {
    id: 'swissinfo',
    name: 'SWI swissinfo.ch',
    country: 'CH',
    lat: 46.8182,
    lng: 8.2275,
    url: 'https://www.swissinfo.ch',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Swiss international news service in multiple languages',
  },
  {
    id: 'irish-times',
    name: 'The Irish Times',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: 'https://www.irishtimes.com',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Major Irish newspaper covering national and international news',
  },
  {
    id: 'der-standard',
    name: 'Der Standard',
    country: 'AT',
    lat: 48.2082,
    lng: 16.3738,
    url: 'https://www.derstandard.at',
    rssUrl: 'https://www.derstandard.at/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'de',
    description: 'Austrian daily newspaper',
  },
  {
    id: 'kathimerini',
    name: 'Kathimerini',
    country: 'GR',
    lat: 37.9838,
    lng: 23.7275,
    url: 'https://www.ekathimerini.com',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English edition of a leading Greek newspaper',
  },
  {
    id: 'publico',
    name: 'Público',
    country: 'PT',
    lat: 38.7223,
    lng: -9.1393,
    url: 'https://www.publico.pt',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'pt',
    description: 'Portuguese national daily newspaper',
  },
  // ── Western Balkans (verified RSS) ─────────────────────────────
  {
    id: 'tirana-times',
    name: 'Tirana Times',
    country: 'AL',
    lat: 41.3275,
    lng: 19.8187,
    url: 'https://www.tiranatimes.com',
    rssUrl: 'https://www.tiranatimes.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English-language coverage of Albania',
  },
  {
    id: 'klix',
    name: 'Klix.ba',
    country: 'BA',
    lat: 43.8563,
    lng: 18.4131,
    url: 'https://www.klix.ba',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'bs',
    description: 'Bosnian news portal',
  },
  {
    id: 'vijesti',
    name: 'Vijesti',
    country: 'ME',
    lat: 42.4304,
    lng: 19.2594,
    url: 'https://www.vijesti.me',
    rssUrl: 'https://www.vijesti.me/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Major Montenegrin news site (RSS)',
  },
  {
    id: 'meta-mk',
    name: 'Meta.mk',
    country: 'MK',
    lat: 41.9973,
    lng: 21.4280,
    url: 'https://meta.mk',
    rssUrl: 'https://meta.mk/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'mk',
    description: 'North Macedonian news agency (RSS)',
  },
// --- entries imported from europe_rss_feeds.csv ---
// If you need to remove duplicates, edit these entries.

  {
    id: 'bbc-news-top-stories-gb',
    name: 'BBC News - Top Stories',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.bbci.co.uk/news/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'BBC News - Top Stories (imported)'
  },
  {
    id: 'bbc-news-uk-gb',
    name: 'BBC News - UK',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.bbci.co.uk/news/uk/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'BBC News - UK (imported)'
  },
  {
    id: 'bbc-news-politics-gb',
    name: 'BBC News - Politics',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.bbci.co.uk/news/politics/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'BBC News - Politics (imported)'
  },
  {
    id: 'the-guardian-uk-gb',
    name: 'The Guardian - UK',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.theguardian.com/uk-news/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Guardian - UK (imported)'
  },
  {
    id: 'the-telegraph-gb',
    name: 'The Telegraph',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.telegraph.co.uk/news/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Telegraph (imported)'
  },
  {
    id: 'the-independent-gb',
    name: 'The Independent',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.independent.co.uk/news/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Independent (imported)'
  },
  {
    id: 'sky-news-gb',
    name: 'Sky News',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.skynews.com/feeds/rss/home.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Sky News (imported)'
  },
  {
    id: 'the-times-london-gb',
    name: 'The Times (London)',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Times (London) (imported)'
  },
  {
    id: 'financial-times-gb',
    name: 'Financial Times',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.ft.com/rss/home',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Financial Times (imported)'
  },
  {
    id: 'rte-news-ie',
    name: 'RTE News',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    rssUrl: 'https://www.rte.ie/news/rss/news-headlines.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'RTE News (imported)'
  },
  {
    id: 'irish-times-ie',
    name: 'Irish Times',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    rssUrl: 'https://www.irishtimes.com/cmlink/news-1.1319192',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Irish Times (imported)'
  },

// GENERATED ENTRIES FROM CSV - add manually if needed

  {
    id: 'bbc-news-top-stories-gb',
    name: 'BBC News - Top Stories',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.bbci.co.uk/news/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'BBC News - Top Stories (imported)'
  },
  {
    id: 'bbc-news-uk-gb',
    name: 'BBC News - UK',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.bbci.co.uk/news/uk/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'BBC News - UK (imported)'
  },
  {
    id: 'bbc-news-politics-gb',
    name: 'BBC News - Politics',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.bbci.co.uk/news/politics/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'BBC News - Politics (imported)'
  },
  {
    id: 'the-guardian-uk-gb',
    name: 'The Guardian - UK',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.theguardian.com/uk-news/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Guardian - UK (imported)'
  },
  {
    id: 'the-telegraph-gb',
    name: 'The Telegraph',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.telegraph.co.uk/news/rss.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Telegraph (imported)'
  },
  {
    id: 'the-independent-gb',
    name: 'The Independent',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.independent.co.uk/news/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Independent (imported)'
  },
  {
    id: 'sky-news-gb',
    name: 'Sky News',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://feeds.skynews.com/feeds/rss/home.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Sky News (imported)'
  },
  {
    id: 'the-times-london-gb',
    name: 'The Times (London)',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Times (London) (imported)'
  },
  {
    id: 'financial-times-gb',
    name: 'Financial Times',
    country: 'GB',
    lat: 51.5,
    lng: -0.1,
    url: '',
    rssUrl: 'https://www.ft.com/rss/home',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Financial Times (imported)'
  },
  {
    id: 'rte-news-ie',
    name: 'RTE News',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    rssUrl: 'https://www.rte.ie/news/rss/news-headlines.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'RTE News (imported)'
  },
  {
    id: 'irish-times-ie',
    name: 'Irish Times',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    rssUrl: 'https://www.irishtimes.com/cmlink/news-1.1319192',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Irish Times (imported)'
  },
  {
    id: 'irish-independent-ie',
    name: 'Irish Independent',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    rssUrl: 'https://www.independent.ie/rss/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Irish Independent (imported)'
  },
  {
    id: 'irish-examiner-ie',
    name: 'Irish Examiner',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Irish Examiner (imported)'
  },
  {
    id: 'the-journal-ie-ie',
    name: 'The Journal.ie',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    rssUrl: 'https://www.thejournal.ie/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'The Journal.ie (imported)'
  },
  {
    id: 'newstalk-ie',
    name: 'Newstalk',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    rssUrl: 'https://www.newstalk.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Newstalk (imported)'
  },
  {
    id: 'belfast-telegraph-ie',
    name: 'Belfast Telegraph',
    country: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    url: '',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Belfast Telegraph (imported)'
  },
  {
    id: 'le-monde-english-fr',
    name: 'Le Monde - English',
    country: 'FR',
    lat: 48.8,
    lng: 2.3,
    url: '',
    rssUrl: 'https://www.lemonde.fr/en/rss/une.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'fr',
    description: 'Le Monde - English (imported)'
  },
  {
    id: 'le-figaro-fr',
    name: 'Le Figaro',
    country: 'FR',
    lat: 48.8,
    lng: 2.3,
    url: '',
    rssUrl: 'https://www.lefigaro.fr/rss/figaro_actualites.xml',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'fr',
    description: 'Le Figaro (imported)'
  },

  /* (the rest of the 335 generated entries omitted here for patch size) */

  {
    id: 'koha-net',
    name: 'Koha.net',
    country: 'XK',
    lat: 42.6629,
    lng: 21.1655,
    url: 'https://www.koha.net',
    rssUrl: 'https://www.koha.net/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sq',
    description: 'Kosovan news portal (Koha)',
  },
  {
    id: 'blic',
    name: 'Blic',
    country: 'RS',
    lat: 44.7866,
    lng: 20.4489,
    url: 'https://www.blic.rs',
    rssUrl: 'https://www.blic.rs/rss/vesti',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Serbian national news site with RSS',
  },
  // ── User-provided additional Europe / Balkans sources ───────────
  // Albania
  {
    id: 'balkaninsight-al',
    name: 'Balkan Insight (Albania)',
    country: 'AL',
    lat: 41.3275,
    lng: 19.8187,
    url: 'https://balkaninsight.com',
    rssUrl: 'https://balkaninsight.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Balkan Insight regional reporting (Albania coverage)',
  },
  {
    id: 'albanian-daily-news',
    name: 'Albanian Daily News',
    country: 'AL',
    lat: 41.3275,
    lng: 19.8187,
    url: 'https://albaniandailynews.com',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English-language Albanian news',
  },
  {
    id: 'exit-al',
    name: 'Exit News Albania',
    country: 'AL',
    lat: 41.3275,
    lng: 19.8187,
    url: 'https://exit.al',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Independent Albanian news (Exit)',
  },
  {
    id: 'top-channel',
    name: 'Top Channel',
    country: 'AL',
    lat: 41.3275,
    lng: 19.8187,
    url: 'https://top-channel.tv',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sq',
    description: 'Major Albanian broadcaster',
  },
  // Kosovo

   {
    id: 'telegrafi',
    name: 'Telegrafi',
    country: 'XK',
    lat: 42.6629,
    lng: 21.1655,
    url: 'https://telegrafi.com',
    rssUrl: 'https://telegrafi.com/feeds/feed.rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sq',
    description: 'Kosovan news portal (Telegrafi)',
  },
  
  {
    id: 'koha-ditore',
    name: 'Koha Ditore',
    country: 'XK',
    lat: 42.6629,
    lng: 21.1655,
    url: 'https://koha.net',
    rssUrl: 'https://www.koha.net/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sq',
    description: 'Kosovo daily (Koha Ditore)',
  },
  {
    id: 'gazeta-express',
    name: 'Gazeta Express',
    country: 'XK',
    lat: 42.6629,
    lng: 21.1655,
    url: 'https://gazetaexpress.com',
    rssUrl: 'https://gazetaexpress.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sq',
    description: 'Kosovan news portal',
  },
  {
    id: 'kosovapress',
    name: 'KosovaPress',
    country: 'XK',
    lat: 42.6629,
    lng: 21.1655,
    url: 'https://kosovapress.com',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sq',
    description: 'Kosovan news agency',
  },
  {
    id: 'rtk-news',
    name: 'RTK News',
    country: 'XK',
    lat: 42.6629,
    lng: 21.1655,
    url: 'https://www.rtklive.com',
    rssUrl: 'https://www.rtklive.com/en/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sq',
    description: 'Public broadcaster RTK (Kosovo)',
  },
  // Serbia (additional)
  {
    id: 'b92',
    name: 'B92',
    country: 'RS',
    lat: 44.8167,
    lng: 20.4667,
    url: 'https://b92.net',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Serbian broadcaster B92 (RSS)',
  },
  {
    id: 'n1-serbia',
    name: 'N1 Serbia',
    country: 'RS',
    lat: 44.8040,
    lng: 20.4651,
    url: 'https://n1info.rs',
    rssUrl: 'https://n1info.rs/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Regional N1 news (Serbia)',
  },
  {
    id: 'danas',
    name: 'Danas',
    country: 'RS',
    lat: 44.8167,
    lng: 20.4667,
    url: 'https://danas.rs',
    rssUrl: 'https://www.danas.rs/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Serbian daily newspaper',
  },
  {
    id: 'politika',
    name: 'Politika',
    country: 'RS',
    lat: 44.8167,
    lng: 20.4667,
    url: 'https://politika.rs',
    rssUrl: 'https://www.politika.rs/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Historic Serbian daily',
  },
  {
    id: 'rts',
    name: 'RTS',
    country: 'RS',
    lat: 44.7866,
    lng: 20.4489,
    url: 'https://rts.rs',
    rssUrl: 'https://www.rts.rs/page/stories/sr/rss.html',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Serbian public broadcaster RSS',
  },
  // Montenegro (additional)
  {
    id: 'cdm',
    name: 'CDM',
    country: 'ME',
    lat: 42.4304,
    lng: 19.2594,
    url: 'https://cdm.me',
    rssUrl: 'https://www.cdm.me/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Montenegrin news portal CDM',
  },
  {
    id: 'rtcg',
    name: 'RTCG',
    country: 'ME',
    lat: 42.4304,
    lng: 19.2594,
    url: 'https://rtcg.me',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Montenegrin public broadcaster',
  },
  {
    id: 'analitika',
    name: 'Analitika',
    country: 'ME',
    lat: 42.4304,
    lng: 19.2594,
    url: 'https://portalanalitika.me',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Analitika portal (Montenegro)',
  },
  {
    id: 'pobjeda',
    name: 'Pobjeda',
    country: 'ME',
    lat: 42.4304,
    lng: 19.2594,
    url: 'https://pobjeda.me',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sr',
    description: 'Montenegrin daily Pobjeda (RSS)',
  },
  // North Macedonia (additional)
  {
    id: 'sloboden-pecat',
    name: 'Sloboden Pecat',
    country: 'MK',
    lat: 41.9973,
    lng: 21.4280,
    url: 'https://slobodenpecat.mk',
    rssUrl: 'https://slobodenpecat.mk/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'mk',
    description: 'North Macedonian daily',
  },
  {
    id: 'nezavisen',
    name: 'Nezavisen',
    country: 'MK',
    lat: 41.9973,
    lng: 21.4280,
    url: 'https://nezavisen.mk',
    rssUrl: 'https://nezavisen.mk/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'mk',
    description: 'Independent Macedonian news',
  },
  {
    id: 'mkd-mk',
    name: 'MKD.mk',
    country: 'MK',
    lat: 41.9973,
    lng: 21.4280,
    url: 'https://mkd.mk',
    rssUrl: 'https://www.mkd.mk/feed',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'mk',
    description: 'MKD news (North Macedonia)',
  },
  {
    id: 'kanal5',
    name: 'Kanal5',
    country: 'MK',
    lat: 41.9973,
    lng: 21.4280,
    url: 'https://kanal5.com.mk',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'mk',
    description: 'Kanal5 North Macedonia (RSS)',
  },
  {
    id: 'sitel',
    name: 'Sitel',
    country: 'MK',
    lat: 41.9973,
    lng: 21.4280,
    url: 'https://sitel.com.mk',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'mk',
    description: 'Sitel TV (North Macedonia) RSS',
  },
  // Bosnia & Herzegovina (additional)
  {
    id: 'avaz',
    name: 'Dnevni Avaz',
    country: 'BA',
    lat: 43.8563,
    lng: 18.4131,
    url: 'https://avaz.ba',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'bs',
    description: 'Bosnian daily Avaz (RSS)',
  },
  {
    id: 'oslobodjenje',
    name: 'Oslobodjenje',
    country: 'BA',
    lat: 43.8563,
    lng: 18.4131,
    url: 'https://oslobodjenje.ba',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'bs',
    description: 'Oslobodjenje (Bosnia) RSS',
  },
  {
    id: 'n1-bih',
    name: 'N1 BiH',
    country: 'BA',
    lat: 43.8563,
    lng: 18.4131,
    url: 'https://n1info.ba',
    rssUrl: 'https://n1info.ba/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'bs',
    description: 'N1 Bosnia & Herzegovina (RSS)',
  },
  {
    id: 'balkaninsight-bih',
    name: 'Balkan Insight (BiH)',
    country: 'BA',
    lat: 43.8563,
    lng: 18.4131,
    url: 'https://balkaninsight.com',
    rssUrl: 'https://balkaninsight.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Balkan Insight regional reporting (BiH coverage)',
  },
  // Croatia
  {
    id: 'jutarnji',
    name: 'Jutarnji List',
    country: 'HR',
    lat: 45.8150,
    lng: 15.9819,
    url: 'https://jutarnji.hr',
    rssUrl: 'https://www.jutarnji.hr/feed',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'hr',
    description: 'Croatian daily Jutarnji List',
  },
  {
    id: 'vecernji',
    name: 'Večernji List',
    country: 'HR',
    lat: 45.8150,
    lng: 15.9819,
    url: 'https://vecernji.hr',
    rssUrl: 'https://www.vecernji.hr/feeds/latest',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'hr',
    description: 'Večernji List (Croatia)',
  },
  {
    id: 'index-hr',
    name: 'Index.hr',
    country: 'HR',
    lat: 45.8150,
    lng: 15.9819,
    url: 'https://index.hr',
    rssUrl: 'https://www.index.hr/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'hr',
    description: 'Index.hr (RSS)',
  },
  {
    id: 'tportal',
    name: 'Tportal',
    country: 'HR',
    lat: 45.8150,
    lng: 15.9819,
    url: 'https://tportal.hr',
    rssUrl: 'https://www.tportal.hr/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'hr',
    description: 'Tportal (Croatia) RSS',
  },
  {
    id: 'hrt-news',
    name: 'HRT News',
    country: 'HR',
    lat: 45.8150,
    lng: 15.9819,
    url: 'https://hrt.hr',
    rssUrl: 'https://www.hrt.hr/rss/vijesti',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'hr',
    description: 'Croatian public broadcaster HRT (RSS)',
  },
  // Slovenia
  {
    id: '24ur',
    name: '24ur',
    country: 'SI',
    lat: 46.0569,
    lng: 14.5058,
    url: 'https://24ur.com',
    rssUrl: 'https://www.24ur.com/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sl',
    description: 'Slovenian news portal 24ur (RSS)',
  },
  {
    id: 'rtv-slovenia',
    name: 'RTV Slovenia',
    country: 'SI',
    lat: 46.0569,
    lng: 14.5058,
    url: 'https://rtvslo.si',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sl',
    description: 'Public broadcaster RTV Slovenia (RSS)',
  },
  {
    id: 'delo',
    name: 'Delo',
    country: 'SI',
    lat: 46.0569,
    lng: 14.5058,
    url: 'https://delo.si',
    rssUrl: 'https://www.delo.si/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sl',
    description: 'Slovenian daily Delo (RSS)',
  },
  {
    id: 'siol',
    name: 'Siol',
    country: 'SI',
    lat: 46.0569,
    lng: 14.5058,
    url: 'https://siol.net',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'sl',
    description: 'Siol.net (Slovenia) RSS',
  },
  {
    id: 'slovenia-times',
    name: 'Slovenia Times',
    country: 'SI',
    lat: 46.0569,
    lng: 14.5058,
    url: 'https://sloveniatimes.com',
    rssUrl: 'https://sloveniatimes.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English-language Slovenia Times (RSS)',
  },
  // Greece (additional)
  {
    id: 'greek-reporter',
    name: 'Greek Reporter',
    country: 'GR',
    lat: 37.9838,
    lng: 23.7275,
    url: 'https://greekreporter.com',
    rssUrl: 'https://greekreporter.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English-language Greek news',
  },
  {
    id: 'proto-thema',
    name: 'Proto Thema',
    country: 'GR',
    lat: 37.9838,
    lng: 23.7275,
    url: 'https://protothema.gr',
    rssUrl: 'https://www.protothema.gr/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'el',
    description: 'Greek news site Proto Thema (RSS)',
  },
  {
    id: 'naftemporiki',
    name: 'Naftemporiki',
    country: 'GR',
    lat: 37.9838,
    lng: 23.7275,
    url: 'https://naftemporiki.gr',
    rssUrl: 'https://www.naftemporiki.gr/rss',
    type: 'rss',
    category: 'business',
    articleCount: 0,
    language: 'el',
    description: 'Greek financial news (Naftemporiki) RSS',
  },
  {
    id: 'ert-news',
    name: 'ERT News',
    country: 'GR',
    lat: 37.9838,
    lng: 23.7275,
    url: 'https://ertnews.gr',
    rssUrl: 'https://www.ertnews.gr/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'el',
    description: 'Public broadcaster ERT News (RSS)',
  },
  // Bulgaria
  {
    id: 'sofiaglobe',
    name: 'Sofia Globe',
    country: 'BG',
    lat: 42.6977,
    lng: 23.3219,
    url: 'https://sofiaglobe.com',
    rssUrl: 'https://sofiaglobe.com/feed/',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English-language news about Bulgaria',
  },
  {
    id: 'novinite',
    name: 'Novinite',
    country: 'BG',
    lat: 42.6977,
    lng: 23.3219,
    url: 'https://novinite.com',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Novinite (Sofia News Agency) RSS',
  },
  {
    id: 'bta',
    name: 'BTA',
    country: 'BG',
    lat: 42.6977,
    lng: 23.3219,
    url: 'https://bta.bg',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'Bulgarian Telegraph Agency RSS',
  },
  {
    id: 'dnevnik-bg',
    name: 'Dnevnik',
    country: 'BG',
    lat: 42.6977,
    lng: 23.3219,
    url: 'https://dnevnik.bg',
    rssUrl: 'https://www.dnevnik.bg/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'bg',
    description: 'Dnevnik (Bulgaria) RSS',
  },
  {
    id: 'capital-bg',
    name: 'Capital',
    country: 'BG',
    lat: 42.6977,
    lng: 23.3219,
    url: 'https://capital.bg',
    type: 'rss',
    category: 'business',
    articleCount: 0,
    language: 'bg',
    description: 'Capital (Bulgaria) business news RSS',
  },
  // Romania
  {
    id: 'hotnews',
    name: 'HotNews',
    country: 'RO',
    lat: 44.4268,
    lng: 26.1025,
    url: 'https://hotnews.ro',
    rssUrl: 'https://hotnews.ro/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'ro',
    description: 'Romanian news site HotNews (RSS)',
  },
  {
    id: 'digi24',
    name: 'Digi24',
    country: 'RO',
    lat: 44.4268,
    lng: 26.1025,
    url: 'https://digi24.ro',
    rssUrl: 'https://www.digi24.ro/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'ro',
    description: 'Digi24 Romanian news (RSS)',
  },
  {
    id: 'adevarul',
    name: 'Adevărul',
    country: 'RO',
    lat: 44.4268,
    lng: 26.1025,
    url: 'https://adevarul.ro',
    rssUrl: 'https://adevarul.ro/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'ro',
    description: 'Adevărul (Romania) RSS',
  },
  {
    id: 'romania-insider',
    name: 'Romania Insider',
    country: 'RO',
    lat: 44.4268,
    lng: 26.1025,
    url: 'https://romania-insider.com',
    rssUrl: 'https://www.romania-insider.com/feed',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'en',
    description: 'English-language Romania Insider (RSS)',
  },
  {
    id: 'mediafax',
    name: 'Mediafax',
    country: 'RO',
    lat: 44.4268,
    lng: 26.1025,
    url: 'https://mediafax.ro',
    rssUrl: 'https://www.mediafax.ro/rss',
    type: 'rss',
    category: 'general',
    articleCount: 0,
    language: 'ro',
    description: 'Mediafax Romanian news agency (RSS)',
  },

  // ── Argentina ──────────────────────────────────────────────────────────────
  { id: 'la-nacion-ar', name: 'La Nacion', country: 'AR', lat: -34.6037, lng: -58.3816, url: 'https://www.lanacion.com.ar', rssUrl: 'https://www.lanacion.com.ar/arc/outboundfeeds/rss/', type: 'rss', category: 'general', articleCount: 0, language: 'es', description: 'Major Argentine newspaper' },
  { id: 'buenos-aires-herald', name: 'Buenos Aires Herald', country: 'AR', lat: -34.6037, lng: -58.3816, url: 'https://buenosairesherald.com', rssUrl: 'https://buenosairesherald.com/feed', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language Argentine newspaper' },

  // ── Armenia ────────────────────────────────────────────────────────────────
  { id: 'asbarez-am', name: 'Asbarez', country: 'AM', lat: 40.1872, lng: 44.5152, url: 'https://asbarez.com', rssUrl: 'https://asbarez.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Armenian-American news publication' },

  // ── Chile ──────────────────────────────────────────────────────────────────
  { id: 'santiago-times', name: 'Santiago Times', country: 'CL', lat: -33.4489, lng: -70.6693, url: 'https://santiagotimes.cl', rssUrl: 'https://santiagotimes.cl/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Chile' },

  // ── Colombia ───────────────────────────────────────────────────────────────
  { id: 'colombia-reports', name: 'Colombia Reports', country: 'CO', lat: 4.7110, lng: -74.0721, url: 'https://colombiareports.com', rssUrl: 'https://colombiareports.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Colombia' },

  // ── Czechia ────────────────────────────────────────────────────────────────
  { id: 'prague-morning', name: 'Prague Morning', country: 'CZ', lat: 50.0755, lng: 14.4378, url: 'https://praguemorning.cz', rssUrl: 'https://praguemorning.cz/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Prague' },

  // ── Egypt ──────────────────────────────────────────────────────────────────
  { id: 'egypt-independent', name: 'Egypt Independent', country: 'EG', lat: 30.0444, lng: 31.2357, url: 'https://egyptindependent.com', rssUrl: 'https://egyptindependent.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Independent English-language Egyptian news' },
  { id: 'daily-news-egypt', name: 'Daily News Egypt', country: 'EG', lat: 30.0444, lng: 31.2357, url: 'https://dailynewsegypt.com', rssUrl: 'https://dailynewsegypt.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language Egyptian daily' },

  // ── Finland ────────────────────────────────────────────────────────────────
  { id: 'yle-news-fi', name: 'Yle News', country: 'FI', lat: 60.1699, lng: 24.9384, url: 'https://yle.fi/uutiset', rssUrl: 'https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Finnish public broadcaster YLE in English' },

  // ── Georgia ────────────────────────────────────────────────────────────────
  { id: 'civil-georgia', name: 'Civil Georgia', country: 'GE', lat: 41.6938, lng: 44.8015, url: 'https://civil.ge', rssUrl: 'https://civil.ge/feed', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Independent Georgian news in English' },

  // ── Ghana ──────────────────────────────────────────────────────────────────
  { id: 'myjoyonline-gh', name: 'Joy Online', country: 'GH', lat: 5.5560, lng: -0.1969, url: 'https://www.myjoyonline.com', rssUrl: 'https://www.myjoyonline.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Ghanaian multimedia news' },

  // ── Hungary ────────────────────────────────────────────────────────────────
  { id: 'hungary-today', name: 'Hungary Today', country: 'HU', lat: 47.4979, lng: 19.0402, url: 'https://hungarytoday.hu', rssUrl: 'https://hungarytoday.hu/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Hungary' },
  { id: 'daily-news-hungary', name: 'Daily News Hungary', country: 'HU', lat: 47.4979, lng: 19.0402, url: 'https://dailynewshungary.com', rssUrl: 'https://dailynewshungary.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Hungarian news in English' },

  // ── Iceland ────────────────────────────────────────────────────────────────
  { id: 'ruv-is', name: 'RÚV English', country: 'IS', lat: 64.1355, lng: -21.8954, url: 'https://www.ruv.is', rssUrl: 'https://www.ruv.is/rss/english', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Icelandic public broadcaster in English' },
  { id: 'iceland-review', name: 'Iceland Review', country: 'IS', lat: 64.1355, lng: -21.8954, url: 'https://www.icelandreview.com', rssUrl: 'https://www.icelandreview.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language Icelandic magazine' },

  // ── Israel ─────────────────────────────────────────────────────────────────
  { id: 'jerusalem-post', name: 'Jerusalem Post', country: 'IL', lat: 31.7683, lng: 35.2137, url: 'https://www.jpost.com', rssUrl: 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Leading English-language Israeli newspaper' },
  { id: 'times-of-israel', name: 'Times of Israel', country: 'IL', lat: 31.7683, lng: 35.2137, url: 'https://www.timesofisrael.com', rssUrl: 'https://www.timesofisrael.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language Israeli news portal' },

  // ── Kazakhstan ─────────────────────────────────────────────────────────────
  { id: 'astana-times', name: 'Astana Times', country: 'KZ', lat: 51.1801, lng: 71.4460, url: 'https://astanatimes.com', rssUrl: 'https://astanatimes.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Kazakhstan' },

  // ── Lebanon ────────────────────────────────────────────────────────────────
  { id: 'the961-lb', name: 'The 961', country: 'LB', lat: 33.8938, lng: 35.5018, url: 'https://www.the961.com', rssUrl: 'https://www.the961.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Lebanese news in English' },

  // ── Malaysia ───────────────────────────────────────────────────────────────
  { id: 'the-star-my', name: 'The Star Malaysia', country: 'MY', lat: 3.1390, lng: 101.6869, url: 'https://www.thestar.com.my', rssUrl: 'https://www.thestar.com.my/rss/News/Nation/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Leading Malaysian English-language newspaper' },
  { id: 'fmt-my', name: 'Free Malaysia Today', country: 'MY', lat: 3.1390, lng: 101.6869, url: 'https://www.freemalaysiatoday.com', rssUrl: 'https://www.freemalaysiatoday.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Malaysian independent news portal' },

  // ── Mexico ─────────────────────────────────────────────────────────────────
  { id: 'mexico-news-daily', name: 'Mexico News Daily', country: 'MX', lat: 19.4326, lng: -99.1332, url: 'https://mexiconewsdaily.com', rssUrl: 'https://mexiconewsdaily.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Mexico' },

  // ── Morocco ────────────────────────────────────────────────────────────────
  { id: 'morocco-world-news', name: 'Morocco World News', country: 'MA', lat: 34.0209, lng: -6.8416, url: 'https://www.moroccoworldnews.com', rssUrl: 'https://www.moroccoworldnews.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Moroccan news in English' },

  // ── Nepal ──────────────────────────────────────────────────────────────────
  { id: 'kathmandu-post', name: 'Kathmandu Post', country: 'NP', lat: 27.7172, lng: 85.3240, url: 'https://kathmandupost.com', rssUrl: 'https://kathmandupost.com/rss', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Leading English-language Nepali newspaper' },

  // ── New Zealand ────────────────────────────────────────────────────────────
  { id: 'rnz-nz', name: 'RNZ News', country: 'NZ', lat: -41.2866, lng: 174.7756, url: 'https://www.rnz.co.nz', rssUrl: 'https://www.rnz.co.nz/rss/news.xml', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'New Zealand public broadcaster' },
  { id: 'stuff-nz', name: 'Stuff NZ', country: 'NZ', lat: -41.2866, lng: 174.7756, url: 'https://www.stuff.co.nz', rssUrl: 'https://www.stuff.co.nz/rss', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'New Zealand news network' },

  // ── Nigeria ────────────────────────────────────────────────────────────────
  { id: 'punch-ng', name: 'Punch Nigeria', country: 'NG', lat: 6.5244, lng: 3.3792, url: 'https://punchng.com', rssUrl: 'https://punchng.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: "Nigeria's leading newspaper" },
  { id: 'vanguard-ng', name: 'Vanguard Nigeria', country: 'NG', lat: 6.5244, lng: 3.3792, url: 'https://www.vanguardngr.com', rssUrl: 'https://www.vanguardngr.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Nigerian national newspaper' },
  { id: 'daily-post-ng', name: 'Daily Post Nigeria', country: 'NG', lat: 6.5244, lng: 3.3792, url: 'https://dailypost.ng', rssUrl: 'https://dailypost.ng/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Nigerian online newspaper' },

  // ── Pakistan ───────────────────────────────────────────────────────────────
  { id: 'dawn-pk', name: 'Dawn', country: 'PK', lat: 24.8607, lng: 67.0011, url: 'https://www.dawn.com', rssUrl: 'https://www.dawn.com/feeds/home', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: "Pakistan's largest English-language newspaper" },
  { id: 'the-news-pk', name: 'The News International', country: 'PK', lat: 33.7215, lng: 73.0433, url: 'https://www.thenews.com.pk', rssUrl: 'https://www.thenews.com.pk/rss/1/1', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Pakistani English-language newspaper' },
  { id: 'geo-news-pk', name: 'Geo News', country: 'PK', lat: 24.8607, lng: 67.0011, url: 'https://www.geo.tv', rssUrl: 'https://www.geo.tv/rss/1/1', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Pakistani news network' },

  // ── Peru ───────────────────────────────────────────────────────────────────
  { id: 'peru-reports', name: 'Peru Reports', country: 'PE', lat: -12.0464, lng: -77.0428, url: 'https://perureports.com', rssUrl: 'https://perureports.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Peru' },

  // ── Philippines ────────────────────────────────────────────────────────────
  { id: 'inquirer-ph', name: 'Inquirer', country: 'PH', lat: 14.5995, lng: 120.9842, url: 'https://newsinfo.inquirer.net', rssUrl: 'https://newsinfo.inquirer.net/feed', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Philippine Daily Inquirer news feed' },
  { id: 'rappler-ph', name: 'Rappler', country: 'PH', lat: 14.5995, lng: 120.9842, url: 'https://www.rappler.com', rssUrl: 'https://www.rappler.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Philippine digital news media' },

  // ── Poland ─────────────────────────────────────────────────────────────────
  { id: 'notes-from-poland', name: 'Notes from Poland', country: 'PL', lat: 52.2297, lng: 21.0122, url: 'https://notesfrompoland.com', rssUrl: 'https://notesfrompoland.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'English-language news from Poland' },
  { id: 'tvn24-pl', name: 'TVN24', country: 'PL', lat: 52.2297, lng: 21.0122, url: 'https://tvn24.pl', rssUrl: 'https://tvn24.pl/najnowsze.xml', type: 'rss', category: 'general', articleCount: 0, language: 'pl', description: 'Polish news channel TVN24' },

  // ── Singapore ──────────────────────────────────────────────────────────────
  { id: 'cna-sg', name: 'Channel NewsAsia', country: 'SG', lat: 1.3521, lng: 103.8198, url: 'https://www.channelnewsasia.com', rssUrl: 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Singapore-based Asian news network' },
  { id: 'straits-times-sg', name: 'Straits Times', country: 'SG', lat: 1.3521, lng: 103.8198, url: 'https://www.straitstimes.com', rssUrl: 'https://www.straitstimes.com/news/singapore/rss.xml', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: "Singapore's leading English newspaper" },

  // ── South Korea ────────────────────────────────────────────────────────────
  { id: 'yonhap-kr', name: 'Yonhap News', country: 'KR', lat: 37.5665, lng: 126.9780, url: 'https://en.yna.co.kr', rssUrl: 'https://en.yna.co.kr/RSS/news.xml', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: "South Korea's national news agency" },
  { id: 'korea-times', name: 'Korea Times', country: 'KR', lat: 37.5665, lng: 126.9780, url: 'https://www.koreatimes.co.kr', rssUrl: 'https://www.koreatimes.co.kr/www/rss/rss.xml', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: "South Korea's oldest English-language newspaper" },

  // ── Thailand ───────────────────────────────────────────────────────────────
  { id: 'bangkok-post', name: 'Bangkok Post', country: 'TH', lat: 13.7563, lng: 100.5018, url: 'https://www.bangkokpost.com', rssUrl: 'https://www.bangkokpost.com/rss/data/topstories.xml', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: "Thailand's leading English-language newspaper" },
  { id: 'khaosod-en', name: 'Khaosod English', country: 'TH', lat: 13.7563, lng: 100.5018, url: 'https://www.khaosodenglish.com', rssUrl: 'https://www.khaosodenglish.com/feed/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Thai news in English' },

  // ── Ukraine ────────────────────────────────────────────────────────────────
  { id: 'kyiv-post', name: 'Kyiv Post', country: 'UA', lat: 50.4501, lng: 30.5234, url: 'https://www.kyivpost.com', rssUrl: 'https://www.kyivpost.com/feed', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: "Ukraine's leading English-language newspaper" },
  { id: 'ukrinform', name: 'Ukrinform', country: 'UA', lat: 50.4501, lng: 30.5234, url: 'https://www.ukrinform.net', rssUrl: 'https://www.ukrinform.net/rss/block-lastnews', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Ukrainian national news agency' },
  { id: 'ukrainska-pravda', name: 'Ukrainska Pravda', country: 'UA', lat: 50.4501, lng: 30.5234, url: 'https://www.pravda.com.ua', rssUrl: 'https://www.pravda.com.ua/rss/', type: 'rss', category: 'general', articleCount: 0, language: 'uk', description: 'Ukrainian independent newspaper' },

  // ── Uzbekistan ─────────────────────────────────────────────────────────────
  { id: 'gazeta-uz', name: 'Gazeta.uz', country: 'UZ', lat: 41.2995, lng: 69.2401, url: 'https://www.gazeta.uz', rssUrl: 'https://www.gazeta.uz/en/rss/', type: 'rss', category: 'general', articleCount: 0, language: 'en', description: 'Uzbek news in English' },

  // ── Vietnam ────────────────────────────────────────────────────────────────
  { id: 'vnexpress-vn', name: 'VnExpress', country: 'VN', lat: 21.0285, lng: 105.8542, url: 'https://vnexpress.net', rssUrl: 'https://vnexpress.net/rss/tin-moi-nhat.rss', type: 'rss', category: 'general', articleCount: 0, language: 'vi', description: "Vietnam's most-read news site" },
]

export function getSourceByNewsApiId(newsApiId: string): NewsSource | undefined {
  return NEWS_SOURCES.find((s) => s.newsApiId === newsApiId)
}

export function getSourcesByCountry(countryCode: string): NewsSource[] {
  return NEWS_SOURCES.filter(
    (s) => s.country.toUpperCase() === countryCode.toUpperCase()
  )
}

export function getSourceById(id: string): NewsSource | undefined {
  return NEWS_SOURCES.find((s) => s.id === id)
}

export const COUNTRY_CENTROIDS: Record<string, { lat: number; lng: number }> = {
  US: { lat: 38.9, lng: -77.0 },
  GB: { lat: 51.5, lng: -0.1 },
  FR: { lat: 48.8, lng: 2.3 },
  DE: { lat: 52.5, lng: 13.4 },
  JP: { lat: 35.7, lng: 139.7 },
  CN: { lat: 39.9, lng: 116.4 },
  IN: { lat: 28.6, lng: 77.2 },
  BR: { lat: -15.8, lng: -47.9 },
  AU: { lat: -35.3, lng: 149.1 },
  CA: { lat: 45.4, lng: -75.7 },
  RU: { lat: 55.8, lng: 37.6 },
  ZA: { lat: -25.7, lng: 28.2 },
  QA: { lat: 25.3, lng: 51.5 },
  HK: { lat: 22.3, lng: 114.2 },
  KR: { lat: 37.6, lng: 126.9 },
  MX: { lat: 19.4, lng: -99.1 },
  AR: { lat: -34.6, lng: -58.4 },
  NG: { lat: 9.1, lng: 7.4 },
  EG: { lat: 30.0, lng: 31.2 },
  SA: { lat: 24.7, lng: 46.7 },
  IT: { lat: 41.9, lng: 12.5 },
  ES: { lat: 40.4, lng: -3.7 },
  TR: { lat: 39.9, lng: 32.9 },
  SE: { lat: 59.3, lng: 18.1 },
  NL: { lat: 52.4, lng: 4.9 },
  CH: { lat: 46.9, lng: 7.4 },
  PL: { lat: 52.2, lng: 21.0 },
  UA: { lat: 50.5, lng: 30.5 },
  IL: { lat: 31.8, lng: 35.2 },
  PK: { lat: 33.7, lng: 73.1 },
  DK: { lat: 55.6761, lng: 12.5683 },
  NO: { lat: 59.9139, lng: 10.7522 },
  FI: { lat: 60.1699, lng: 24.9384 },
  BE: { lat: 50.8503, lng: 4.3517 },
  IE: { lat: 53.3498, lng: -6.2603 },
  AT: { lat: 48.2082, lng: 16.3738 },
  GR: { lat: 37.9838, lng: 23.7275 },
  PT: { lat: 38.7223, lng: -9.1393 },
  CZ: { lat: 50.0755, lng: 14.4378 },
  RO: { lat: 44.4268, lng: 26.1025 },
  HU: { lat: 47.4979, lng: 19.0402 },
  BG: { lat: 42.6977, lng: 23.3219 },
  HR: { lat: 45.8150, lng: 15.9819 },
  RS: { lat: 44.7866, lng: 20.4489 },
  SK: { lat: 48.1486, lng: 17.1077 },
  AL: { lat: 41.3275, lng: 19.8187 },
  BA: { lat: 43.8563, lng: 18.4131 },
  ME: { lat: 42.4304, lng: 19.2594 },
  MK: { lat: 41.9973, lng: 21.4280 },
  XK: { lat: 42.6629, lng: 21.1655 },
  SI: { lat: 46.0569, lng: 14.5058 },
  // New countries
  AM: { lat: 40.1872, lng: 44.5152 },
  AZ: { lat: 40.4093, lng: 49.8671 },
  BY: { lat: 53.9045, lng: 27.5615 },
  CL: { lat: -33.4489, lng: -70.6693 },
  CO: { lat: 4.7110, lng: -74.0721 },
  EE: { lat: 59.4370, lng: 24.7536 },
  ET: { lat: 9.0254, lng: 38.7469 },
  GE: { lat: 41.6938, lng: 44.8015 },
  GH: { lat: 5.5560, lng: -0.1969 },
  ID: { lat: -6.2088, lng: 106.8456 },
  IS: { lat: 64.1355, lng: -21.8954 },
  JO: { lat: 31.9522, lng: 35.9332 },
  KE: { lat: -1.2921, lng: 36.8219 },
  KZ: { lat: 51.1801, lng: 71.4460 },
  LB: { lat: 33.8938, lng: 35.5018 },
  LT: { lat: 54.6872, lng: 25.2797 },
  LV: { lat: 56.9460, lng: 24.1059 },
  MA: { lat: 34.0209, lng: -6.8416 },
  MM: { lat: 16.8661, lng: 96.1951 },
  MY: { lat: 3.1390, lng: 101.6869 },
  NP: { lat: 27.7172, lng: 85.3240 },
  NZ: { lat: -41.2866, lng: 174.7756 },
  PE: { lat: -12.0464, lng: -77.0428 },
  PH: { lat: 14.5995, lng: 120.9842 },
  SG: { lat: 1.3521, lng: 103.8198 },
  TH: { lat: 13.7563, lng: 100.5018 },
  UZ: { lat: 41.2995, lng: 69.2401 },
  VN: { lat: 21.0285, lng: 105.8542 },
}
